language: php
services:
- mysql
php:
- 7.1
before_script:
- cp app/config/parameters.yml.travis app/config/parameters.yml
- composer install
- php bin/console doctrine:database:create --env=test
- php bin/console doctrine:schema:create --env=test
- php bin/console doctrine:fixtures:load -n --env=test
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 deploy-key
- ssh-add deploy-key
- git remote add deploy $DEPLOY_REPO_URI
- git push deploy master
before_install:
- openssl aes-256-cbc -K $encrypted_1f94ce712141_key -iv $encrypted_1f94ce712141_iv
  -in deploy-key.enc -out deploy-key -d
