#Front
front.api.message.coordinates.list:
    path: /front/api/message/coordinates/list
    methods: [GET]
    defaults:
        _controller: AppBundle:Front/Api/Message:getLatestMessagesCoordinates

front.api.message.list:
    path: /front/api/message/list/{lat}/{long}
    methods: [GET]
    defaults:
        _controller: AppBundle:Front/Api/Message:getMessages

front.api.message.create:
    path: /front/api/message
    methods: [POST]
    defaults:
        _controller: AppBundle:Front/Api/Message:createMessage

front.api.comment.create:
    path: /front/api/message/{message_id}/comment
    methods: [POST]
    defaults:
        _controller: AppBundle:Front/Api/Comment:createComment